### ISSUE TITLE
Using secure sockets

### ISSUE THREAD

**Issue by geekytime** [an-sh/ws-messaging#1]
I'd love to use ws-messaging, but I need to be able to use secure sockets, and use my own cert and key.

It looks like I can pass an `https` instance as the `{server}` option into `ws-messaging` server, and it'll get passed down to `ws`, as ws expects in [this example](https://github.com/websockets/ws/blob/master/examples/ssl.js).

It looks like [the `ws` Client also accepts an options object](https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket) that can include `cert`, and `key`, so I could use my own certs. Unfortunately, it looks like `ws-messaging` [doesn't pass anything for that option](https://github.com/an-sh/ws-messaging/blob/master/src/Client.js#L338) when it instantiates the WebSocket instance.

Would you be willing to consider adding this functionality to ws-messaging, or reviewing a PR that adds this functionality?

**Comment by an-sh** [comment]
On Thu, 29 Dec 2016 09:55:12 -0800
Chris Jaynes <notifications@github.com> wrote:

> I'd love to use ws-messaging, but I need to be able to use secure
> sockets, and use my own cert and key.
> 
> It looks like I can pass an `https` instance as the `{server}` option
> into `ws-messaging` server, and it'll get passed down to `ws`, as ws
> expects in [this
> example](https://github.com/websockets/ws/blob/master/examples/ssl.js).
> 
> It looks like [the `ws` Client also accepts an options
> object](https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket)
> that can include `cert`, and `key`, so I could use my own certs.
> Unfortunately, it looks like `ws-messaging` [doesn't pass anything
> for that
> option](https://github.com/an-sh/ws-messaging/blob/master/src/Client.js#L338)
> when it instantiates the WebSocket instance.
> 
> Would you be willing to consider adding this functionality to
> ws-messaging, or reviewing a PR that adds this functionality?
> 

On a server side socket creation is done inside ws, so the _open
function is not called at all and browser client + node server should
work. If your case is node.js server to server secure communication,
then passing additional options to non-w3c socket constructor is really
missing. PR are welcomed on this.

-- 
Andrey
